### ISSUE TITLE
`location.query` changes on link hover inside of route preload functions

### ISSUE THREAD

**Issue by spiffytech** [solidjs/solid-router#476]
### Describe the bug

If I reference `location.query` from inside a route preload function, I'll see that signal change every time the user hovers over a link, even if they don't click that link.

This only happens for effects that live inside the preload function. Anything I return from the preload function behaves normally when accessed from the route component.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-evsys4?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Create a route preload function
2. Create an effect that logs the signal `location.query`, provided by the arguments to the preload function
3. Observe that if you hover over any link on the page, the signal changes, even if the page's query params haven't actually changed.
4. Return `location.query`, or some derived value, from the preload function. Observe that it does _not_ react to link hover in the component's scope.

### Expected behavior

Signal only changes when address bar changes. Signal always reflects value in address bar.

### Platform

- OS: Linux
- Browser: Vivaldi, Chromium

### Additional context

I discovered this while creating a resource that refreshes when the query params change.

**Comment by spiffytech** [comment]
Oh, bonus bug (or same one?): if the route preload function returns a resource that uses `location.query` as its source signal, the component never sees that resource update: [Stackblitz](https://stackblitz.com/edit/solidjs-templates-2q5lhv?file=src%2Findex.tsx)

**Comment by ryansolid** [comment]
There are a couple things going on here. We support reactivity in the preload function as backwards compat with pre 0.10 versions. In those cases you should turn off preload globally. It just won't work properly. I don't believe it is the createEffect logging that is causing the additional logs but that we just run the whole function whenever you hover. This just run the preload function is at odds with the previous approach, but its why the previous approach never did preloading.

Under new best practices you shouldn't be making reactive primitives or returning stuff from preload function. It is basically only for legacy support. 

`location.query` isn't the signal but the query is a getter object itself. So we don't detect if the query changes but rather if individual fields change. This is why stringify works as it accesses all the fields. Otherwise I would just recommend listening to the field you care about.

**Comment by spiffytech** [comment]
Ah, I didn't catch the semantic change with the move to ~~load~~ preload.

Re: createEffect: yep, now that I know what to look for, I can see that it's just the whole preload function running over and over.

Can you clarify what you mean by not "returning stuff" from preload functions? The docs (including the migration docs you linked) show returning a resource. What specifically is the legacy behavior I should avoid?

**Comment by ryansolid** [comment]
> Can you clarify what you mean by not "returning stuff" from preload functions? The docs (including the migration docs you linked) show returning a resource. What specifically is the legacy behavior I should avoid?

Basically everything in that section of the docs. That was a bandaid to get the existing behavior back for those who couldn't upgrade.

What you should be doing now is use `cache` functions in preload and pass those to `createAsync` calls in the components.

**Comment by spiffytech** [comment]
Got it, thanks!
